spring:
  redis:
    host: "47.98.139.92"
    port: 6379
    password: cnmlgb
  datasource:
    url: "jdbc:mysql://47.98.139.92:3306/sinoinfo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "root"
    password: 123456
    driver-class-name: "com.mysql.jdbc.Driver"
collect:
  enable: true
  listenPort: 8888
  consumeThreadCount: 1
  idleTimeout: 600
app:
  system: "local"
  dev: false
  watch: true
  authCode: "1234567890A"
  messageQueueCount: 1
  messageQueueSize: 100
  asyncThreads: 10